package server;

public enum Endpoint {
    GET_ALL_TASKS, GET_ALL_SUBTASKS, GET_ALL_EPICS, REMOVE_ALL_TASKS, REMOVE_ALL_SUBTASKS, REMOVE_ALL_EPICS,
    GET_TASK, GET_SUBTASK, GET_EPIC, ADD_OR_UPDATE_TASK, ADD_OR_UPDATE_SUBTASK, ADD_OR_UPDATE_EPIC,
    REMOVE_TASK, REMOVE_SUBTASK, REMOVE_EPIC, HISTORY, GET_PRIORITIZED_TASKS, GET_EPIC_SUBTASKS, UNKNOWN
}
